#!/bin/sh
set -eu

root="$(dirname "$0")/.."
cd "$root"

out_root="${OUT_DIR:-${1:-docs/examples}}"

# tests/cmd.rs calls this from inside the `cmd` test run; re-running that run would recurse.
if [ "${LETS_GEN_EXAMPLES_SKIP_TEST:-0}" != "1" ]; then
  cargo nextest run --locked --test cmd
fi

# A case whose tool is absent was skipped by the test run, so its golden is unverified here.
have_requirements() {
  while IFS= read -r tool || [ -n "$tool" ]; do
    [ -n "$tool" ] || continue
    command -v "$tool" >/dev/null 2>&1 || return 1
  done <"$1"
  return 0
}

mkdir -p "$out_root"

for dir in tests/cmd/*/; do
  verb="$(basename "$dir")"
  out="${out_root}/${verb}.md"
  {
    echo "<!-- generated by \`just docs\` from tests/cmd/${verb}/ — do not hand-edit -->"
    echo
    first=1
    # Bytewise: en_US collation puts `a.toml` before `a-b.toml` and C after, so docs differed per box.
    for case in $(find "$dir" -maxdepth 1 \( -name '*.trycmd' -o -name '*.toml' \) | LC_ALL=C sort); do
      requires="${case%.*}.requires"
      if [ -f "$requires" ] && ! have_requirements "$requires"; then
        continue
      fi
      if [ "$first" -eq 0 ]; then
        echo
      fi
      first=0
      case "$case" in
        *.toml)
          # Exit code, stdin and stderr stay in, or a refusal would read as a silent success.
          bin=$(sed -n 's/^bin\.name = "\(.*\)"$/\1/p' "$case")
          # Quoted so every `$` line runs when pasted; CR, LF and tab keep their escape in `$'...'`.
          args=$(awk '
            function single(s,   i, c, t) {
              t = "\047"
              for (i = 1; i <= length(s); i++) {
                c = substr(s, i, 1)
                t = t (c == "\047" ? "\047\\\047\047" : c)
              }
              return t "\047"
            }
            function ansi(s,   i, c, t) {
              t = "$\047"
              for (i = 1; i <= length(s); i++) {
                c = substr(s, i, 1)
                t = t (c == "\047" ? "\\\047" : c)
              }
              return t "\047"
            }
            /^args = \[.*\]$/ {
              line = substr($0, 9, length($0) - 9)
              out = ""
              n = length(line)
              i = 1
              while (i <= n) {
                q = substr(line, i, 1)
                if (q != "\"" && q != "\047") { i++; continue }
                i++
                arg = ""; raw = ""; control = 0
                # A TOML literal string has no escapes: everything up to the next quote is the arg.
                if (q == "\047") {
                  while (i <= n && substr(line, i, 1) != "\047") { arg = arg substr(line, i, 1); i++ }
                  i++
                }
                while (q == "\"" && i <= n) {
                  c = substr(line, i, 1)
                  if (c == "\\") {
                    e = substr(line, i + 1, 1)
                    raw = raw c e
                    i += 2
                    if (e == "n" || e == "r" || e == "t") control = 1
                    else arg = arg e
                    continue
                  }
                  i++
                  if (c == "\"") break
                  arg = arg c; raw = raw c
                }
                if (control) word = ansi(raw)
                else if (arg != "" && arg !~ /[^A-Za-z0-9_.\/:=@%+,-]/) word = arg
                else word = single(arg)
                out = out (out == "" ? "" : " ") word
              }
              print out
            }' "$case")
          code=$(sed -n 's/^code = \([0-9][0-9]*\)$/\1/p' "$case")
          stdin="${case%.toml}.stdin"
          printf '```console\n$ %s %s' "$bin" "$args"
          if [ -s "$stdin" ]; then
            printf " <<'EOF'\n"
            cat "$stdin"
            printf 'EOF\n'
          else
            printf '\n'
          fi
          [ -n "$code" ] && printf '? %s\n' "$code"
          stdout="${case%.toml}.stdout"
          [ -f "$stdout" ] && cat "$stdout"
          stderr="${case%.toml}.stderr"
          [ -f "$stderr" ] && cat "$stderr"
          printf '\n```\n'
          ;;
        *)
          cat "$case"
          ;;
      esac
    done
  } >"$out"
done
